### PR TITLE
Implemented Login Signup and Forgot password functionality

### PR DESCRIPTION
**Pull request by Akashsah2003**
## Overview

1. This PR fixes or fixes part of #57 .
2. This PR does the following: [Explain here what your PR does and why]

- Implemented Login functionality with proper error handling.
- Implemented functionality for remember me.
- Implemented functionality for forgot password.
- Implemented Sign up functionality.
- Properly evaluated email address and password with proper error handling.
- Implemented Logout functionality.
- Added loader in login and signup page.

## Essential Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

https://github.com/bsoc-bitbyte/resource-sharing/assets/73382164/c6c0cd62-cfce-4f6f-95d3-a637e6c58bcf

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

**Comment by Akashsah2003** [comment]
@Anurag607 @sambhavgupta0705 Please review the pr also for valid institute email id I have used regex such that 22bcs019 or 20bec119 these types of email ids will be valid. Is there anymore email ids that we can consider valid or is this fine?

**Comment by sambhavgupta0705** [comment]
@Anurag607 @Akashsah2003 well we are making this valid only for students or should we also do it for all staff of institute

**Comment by sambhavgupta0705** [comment]
@Akashsah2003 just saw the preview and just a huge applause how you have handled all this functions .
Really impressive.

**Comment by Anurag607** [comment]
> @Anurag607 @Akashsah2003 well we are making this valid only for students or should we also do it for all staff of institute

well let's keep it for the students for the time being, will change it later if need be.

**Comment by Anurag607** [comment]
@Akashsah2003 in the video i noticed that their are no warning when you entered the invalid email....please add proper warning to be displayed above the form (above Name), also highlight the input field which is invalid with red borders...so whenever a wrong input is entered the field's border turn red

**Comment by Anurag607** [comment]
@Akashsah2003 the warnings are  to be displayed above the form (above Name) and please highlight them like **you can change the div bg-color to red give it border radius and so on, so that it immediately draws the user's attention**, also highlight the input field which is invalid with red borders...so whenever a wrong input is entered the field's border turn red

**Comment by Akashsah2003** [comment]
@Anurag607 @sambhavgupta0705 I did the asked changes. This is the preview.

https://github.com/bsoc-bitbyte/resource-sharing/assets/73382164/ebfea244-f74a-4372-9223-5880ffdbe34d

Please review and merge the pr.

**Comment by sambhavgupta0705** [comment]
@Akashsah2003 ask the maintainers to have a look.
Don't always say to `review and merge the pr` sometimes it leaves a bad impression 🙂

**Comment by Akashsah2003** [comment]
> @Akashsah2003 ask the maintainers to have a look first. Don't always say to `review and merge the pr` sometimes it leaves a bad impression 🙂

Ok thank you for guiding me. I will keep that in mind.

**Comment by Anurag607** [comment]
@sambhavgupta0705 I think everything checks out, if you have any other suggestions then please share else we can perhaps go ahead with the merge

**Comment by sambhavgupta0705** [comment]
@Akashsah2003 inspite of `firebase : error` can we have a custom error there??

**Comment by Akashsah2003** [comment]
> @Akashsah2003 inspite of `firebase : error` can we have a custom error there??


https://github.com/bsoc-bitbyte/resource-sharing/assets/73382164/8aa903a5-f031-4326-8265-e5346c94cc1a

@sambhavgupta0705 @Anurag607 Please take a look.

**Comment by sambhavgupta0705** [comment]
@Akashsah2003 @Anurag607 LGTM

**Review by sambhavgupta0705 — APPROVED** [review]
LGTM

**Comment by Anurag607** [comment]
Then let's close the issue

**Comment by Akashsah2003** [comment]
@sambhavgupta0705 @Anurag607 Kindly tag the pr.

**Pull request merged**
