### PR TITLE
added the preview page in materials page

### LINKED ISSUE #51: [Feature Request]: A new page for displaying the details corresponding
This issue will ensure that the users have a brief (but necessary) knowledge regarding the material, allowing them to be more selective in their search.

- Create a page **(the reference image is attached bellow)** while maintaining the color scheme of the site.
- Make sure the page is responsive.
- Add a button for re-directing users to the pdf users (like: Read Now).
- Also maintain the code structure, you can visit the other components to see how they were implemented

You can refer to the below image for inspiration...**make sure to keep the design structure similar**. But there are minor changes here and there.

- **Like you can replace the buy with button with the button required for redirection**.
- you can remove size, publication and size
- binding can be replaced with type denoting the type of material (handwrittern notes, pdf lecture notes, pdf books and so on)

### On Desktop: 
image

### On Mobile: 
image
image

### PR DESCRIPTION
**Pull request by shramanpaul**
## Overview

1. This PR fixes or fixes part of [#51 ].
2. This PR does the following: [uses states and props to create the preview page which is responsive and adaptable to new data ]

## Essential Checklist

- [x] The PR title starts with "Fix #51 : ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #51 ".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)

 @Anurag607  PTAL

### CODE REVIEW

**Review by Anurag607 — CHANGES_REQUESTED** [review]

**Comment by Anurag607** [comment]
@shramanpaul any updates?

**Comment by Anurag607** [comment]
@shramanpaul  there have been some changes so make sure to pull first

**Comment by shramanpaul** [comment]
@Anurag607  I will submit the PR  today.

**Comment by shramanpaul** [comment]
@Anurag607  made the changes PTAL

**Review by Anurag607 — APPROVED** [review]

**Comment by Anurag607** [comment]
@sambhavgupta0705 everything checks out on my end, please take a look and let us know if you find any necessary changes

**Comment by sambhavgupta0705** [comment]
@Anurag607 LGTM🚀

**Review by sambhavgupta0705 — APPROVED** [review]

**Pull request merged**
