### PR TITLE
[Feat]: Placed content.jsx file in components folder

### PR DESCRIPTION
**Pull request by parthksingh1**
## Overview

1. This PR fixes or fixes part of #27 
2. This PR does the following: Placed content.jsx file in component folder

## Essential Checklist

- [X] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [X] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [X] The PR is made from a branch that's **not** called "main/master".

### CODE REVIEW

**Comment by sambhavgupta0705** [comment]
@parthksingh1 try to run it locally I think it will give some errors

**Comment by sambhavgupta0705** [comment]
change the context.jsx call in index,js also

**Comment by parthksingh1** [comment]
It's been deleted from pages and moved to components Folder

**Comment by parthksingh1** [comment]
The task has been completed. Please review it, and kindly let me know if any further adjustments are required.

**Comment by sambhavgupta0705** [comment]
@parthksingh1 I don't think so.As github show the deleted files also

**Comment by sambhavgupta0705** [comment]
@parthksingh1 any updates?

**Comment by parthksingh1** [comment]
Yes, sir. The merge conflicts have been resolved, and I made the commit earlier this morning.

**Comment by sambhavgupta0705** [comment]
ok

**Comment by sambhavgupta0705** [comment]
@Anurag607 could please check this once

**Review by sambhavgupta0705 — APPROVED** [review]

**Pull request merged**
