### PR TITLE
Login&signUp darkmode bug #46 fix

### LINKED ISSUE #46: [BUG]: In login page , background color does not change in dark mode
### Describe the bug

In login page and signup page, when switched to the dark mode, the background color of the input details box is not changing to dark color. So, the login credentials user entered in the input box and  "Login","SignUp", "IIITDMJ" text is is not visible.

### Steps To Reproduce

_No response_

### Expected Behavior

When the user switches to the dark mode, the background-color of the input is expected to change to dark color. So that the login credentials, "Login","SignUp", "IIITDMJ" text  will be visible to the user.

### Screenshots/Videos

image

image

### What device are you using?

Desktop, Mobile

### Operating System

Windows, Android

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AkashPaloju**
## Overview

1. This PR fixes #46 
2. This PR does the following: Changed  the text color of "Login","signUp", and input credentials in dark mode to make it visible

## Essential Checklist

- [x] The PR title starts with Bugnum , followed by a short, clear summary of the changes. 
- [x] "Allow edits from maintainers" is checked.
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

image
 
image

https://github.com/bsoc-bitbyte/resource-sharing/assets/119884665/521bbb80-0a24-4cea-ba2f-ce46b62c2534

@sambhavgupta0705 Please review it and kindly let me know if any further adjustments are required

### CODE REVIEW

**Comment by sambhavgupta0705** [comment]
@Anurag607 PTAL

**Comment by sambhavgupta0705** [comment]
@AkashPaloju just change the property of title in dark mode .
The UI made by you is not looking that good so just for now change the css proeprty

**Comment by AkashPaloju** [comment]
@sambhavgupta0705 PTAL to this new commit

**Comment by sambhavgupta0705** [comment]
@AkashPaloju Please provide a preview

**Comment by AkashPaloju** [comment]
> @AkashPaloju Please provide a preview

@sambhavgupta0705 I have uploaded the preview video on updated PR comment

**Comment by sambhavgupta0705** [comment]
@AkashPaloju I think you have find one more issue. It would be nice if you could raise an issue for it.

**Comment by AkashPaloju** [comment]
> @AkashPaloju I think you have find one more issue. It would be nice if you could raise an issue for it.

@sambhavgupta0705 Yes, but my academics are bad till now and Endsem is around the corner, Should I simply raise an issue for now

**Comment by sambhavgupta0705** [comment]
@AkashPaloju yes raise an issue for now and you can work on it after your Endsems 
Good luck for you Endsems🙌

**Pull request merged**
