### PR TITLE
Redirection of login button

### LINKED ISSUE #31: [Feature Request]: Add redirection for login page
### Is your feature request related to a problem? Please describe.

On clicking login button the login page must be called .
The page has been made you just need to write function that on clicking the button the user must be redirected to `/login` url .

### Describe the solution you'd like

.

### Describe alternatives you've considered

_No response_

### Developer Help

Ask for help whenever needed.

### PR DESCRIPTION
**Pull request by shramanpaul**
## Overview

1. This PR fixes or fixes  #31 .
2. This PR does the following: [Redirection of the pages by Routing through the buttons]

## Essential Checklist

- [x] The PR is made from a branch that's "redirection of login button".

## Proof that changes are correct

https://github.com/bsoc-bitbyte/resource-sharing/assets/110323017/001491a0-403c-46f5-9985-89361e01aea7

@Anurag607  @sambhavgupta0705 
Please review the PR made

### CODE REVIEW

**Comment by sambhavgupta0705** [comment]
@shramanpaul #31 is assigned to other person.
Let him work on that issue

**Comment by shramanpaul** [comment]
Sorry by mistake I made the the PRs for both I am updating the PR in the following only for issue #31 .

**Comment by shramanpaul** [comment]
Updated the PR for #31

**Comment by sambhavgupta0705** [comment]
@shramanpaul revert your changes of #30 it would be good to merge it in this one only.
Will close issue #30 for now.

**Review by sambhavgupta0705 — APPROVED** [review]

**Pull request merged**
