### PR TITLE
Made the dashboard component

### PR DESCRIPTION
**Pull request by Kushdapush**
## Overview

1. This PR fixes or fixes part of #63 .
2. This PR does the following: Designed and Implemented the dashboard component 

## Essential Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct
with sidebar open
image
with sidebar closed
image

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

**Comment by Kushdapush** [comment]
@Anurag607 @sambhavgupta0705 sir PTAL

**Comment by sambhavgupta0705** [comment]
@Kushdapush I have a suggestion that in the navbar we can have the name of the user instead of the dashboard written and when he clicks on it he is redirected to the dashboard

**Comment by Kushdapush** [comment]
WhatsApp Image 2023-07-11 at 15 50 17

@sambhavgupta0705  is this okay

**Comment by sambhavgupta0705** [comment]
@Kushdapush @Tusharjain123 will be reviewing this work

**Comment by Kushdapush** [comment]
@Tusharjain123 sir please review the changes

**Comment by Tusharjain123** [comment]
@Kushdapush any updates

**Comment by Kushdapush** [comment]
image
here's the dark mode version

**Comment by Kushdapush** [comment]
https://github.com/bsoc-bitbyte/resource-sharing/assets/129064700/c8c5e2de-2d7e-41bf-9eed-760b71f9b095
here's the UI

**Comment by Kushdapush** [comment]
@Tusharjain123 @sambhavgupta0705 @Anurag607 , please review my latest commit and let me know if any changes are required.

**Comment by Kushdapush** [comment]
@sambhavgupta0705 PTAL now

**Comment by Kushdapush** [comment]
@Tusharjain123 sir please review the latest commit

**Comment by sambhavgupta0705** [comment]
@Kushdapush merge conflicts

**Comment by Kushdapush** [comment]
Done sir

**Comment by sambhavgupta0705** [comment]
Preview?? @Kushdapush

**Comment by Kushdapush** [comment]
https://github.com/bsoc-bitbyte/resource-sharing/assets/129064700/da713c57-b0a9-44b1-92da-90862716b5fc

**Comment by Kushdapush** [comment]
here's the preview

**Comment by Tusharjain123** [comment]
@Kushdapush can you make the numbers alignment center and somewhat enlarge them so that it looks good
What you say @sambhavgupta0705 @Anurag607

**Comment by sambhavgupta0705** [comment]
jokes apart first change the name you have used and then share a preview .just write xyz
Don't use any such name please as it may lead to severe consequences

**Comment by sambhavgupta0705** [comment]
@Kushdapush

**Comment by Kushdapush** [comment]
ok sir, sorry!

**Comment by Kushdapush** [comment]
imagehow does this look sir?

**Comment by Kushdapush** [comment]
image
Centered the Numbers as well

**Review by sambhavgupta0705 — APPROVED** [review]

**Pull request merged**
