### PR TITLE
feat: Add PDFViewer component

### PR DESCRIPTION
**Pull request by jainvedant392**
## Overview

1. This PR fixes or fixes part of #52.
2. This PR does the following: [Explain here what your PR does and why]
- Added a react-pdf-viewer as **PDFViewer** in *components*.
- Added a pdf file as *src\assets\fonts\2.2_Scales.pdf* to show the working of pdf-viewer.
- Added **Route** in *App.jsx* as *"/pdfviewer"*, for viewing the pdf file.

## Essential Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct
image
image

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

**Review by sambhavgupta0705 — APPROVED** [review]
LGTM the basic functionality works @Anurag607 just request the changes you want in this PR

**Comment by Anurag607** [comment]
@jainvedant392 

image

as you can see in this image that the file is getting clipped in dual mode at 100% zoom. please look into it.

**Comment by Anurag607** [comment]
@jainvedant392 is it possible to show the pdf in dual mode by default...if so then kindly make it so

**Comment by Anurag607** [comment]
@jainvedant392 also remove the pdf from the pdf and transfer it to the public folder

**Comment by jainvedant392** [comment]
Sure @Anurag607

**Comment by jainvedant392** [comment]
> @jainvedant392 
> 
> image
> 
> **as you can see in this image that the file is getting clipped in dual mode at 100% zoom. please look into it.**

In this pdf viewer, the user can set the zoom as well as the page mode, whether single page or dual page at a time

**Comment by jainvedant392** [comment]
> @jainvedant392 is it possible to show the pdf in dual mode by default...if so then kindly make it so

Yeah sure, I'll look into it

**Comment by Anurag607** [comment]
> > @jainvedant392
> > image
> > **as you can see in this image that the file is getting clipped in dual mode at 100% zoom. please look into it.**
> 
> In this pdf viewer, the user can set the zoom as well as the page mode, whether single page or dual page at a time

Regardless, maybe you can adjust the width so that at least in 100% the pdf is completely visible

**Comment by jainvedant392** [comment]
Ok ok I got it

**Comment by jainvedant392** [comment]
I'll increase the width of the viewer

**Comment by sambhavgupta0705** [comment]
@jainvedant392 look for merge conflicts

**Comment by jainvedant392** [comment]
@Anurag607 and @sambhavgupta0705, all the requested changes have been made.
The pdf-viewer now displays 2 pages at a time by default.
There is no wrapping of pdf in 100% zoom mode.
Also, the pdf file is transferred to public folder.

**Comment by jainvedant392** [comment]
sure

**Comment by sambhavgupta0705** [comment]
After making the changes also add a final preview

**Pull request merged**
