### PR TITLE
Added preloader for materialPages

### PR DESCRIPTION
**Pull request by AyushGovil**
## Overview

1. This PR fixes or fixes part of #49.
2. This PR does the following: Adds preloader for every material page.

## Essential Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

Proof that the fix is working 

https://github.com/bsoc-bitbyte/resource-sharing/assets/33975149/62752c8c-bb1e-4d9c-8716-02813b9eed9e

## PR Pointers
- Test the code by adding the following code in App.jsx file. 

const MaterialsPage = React.lazy(() => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(import('./MaterialsPage'));
    }, 3000); // Simulate a 3-second delay
  });
});

### CODE REVIEW

**Comment by AyushGovil** [comment]
Need review.

**Comment by sambhavgupta0705** [comment]
https://github.com/bsoc-bitbyte/resource-sharing/pull/50#issuecomment-1600293249

**Comment by sambhavgupta0705** [comment]
@AyushGovil any updates??

**Comment by AyushGovil** [comment]
Hi @sambhavgupta0705, I would need review on this code. Based on the comment you made #50. I have used react suspense to add preloader for each material page. Let me know exactly if I have missed something.

**Comment by sambhavgupta0705** [comment]
@AyushGovil resolve the merge conflicts

**Comment by AyushGovil** [comment]
@sambhavgupta0705 , I have resolved the conflicts

**Comment by AyushGovil** [comment]
https://github.com/bsoc-bitbyte/resource-sharing/assets/33975149/9141dc60-c2f1-48f2-98eb-a7197000d127

Hi @sambhavgupta0705 , here is the preview. Request you to look into this pr to avoid merge conflicts again due to new code merges.

**Comment by Anurag607** [comment]
@sambhavgupta0705 yes, i think it matches with the theme. we can refine it later as well if the need arises

**Pull request closed without merging**
