### PR TITLE
footer code 

### LINKED ISSUE #4: Create a Footer for the site
The footer needs to have:

1) A link to the institute website
2) Our Contact details
3) An input form for subscription purpose
The above mentioned components are a must....
Any other addition can be shared in the comment section.

### PR DESCRIPTION
**Pull request by RISHIKESHk07**
FOOTER 
- Includes a subscription bar, links to social media accounts and college website
- Responsive on all devices
- Added colors in tailwind config file

fixes #4

### CODE REVIEW

**Comment by sambhavgupta0705** [comment]
@RISHIKESHk07 don't forget to link the issue 😄

**Comment by sambhavgupta0705** [comment]
@RISHIKESHk07 can you please share a preview

**Comment by RISHIKESHk07** [comment]
https://github.com/bsoc-bitbyte/resource-sharing/assets/117551967/4f196d71-84ef-4787-9246-f6721c8a39b4

**Comment by sambhavgupta0705** [comment]
@RISHIKESHk07 Try something different in terms of font

**Comment by sambhavgupta0705** [comment]
@RISHIKESHk07 first take a git pull

**Review by sambhavgupta0705 — APPROVED** [review]
Done 👍🏻

**Pull request merged**
