### PR TITLE
feat(frontend): Designed and added the Favicon for the website

### LINKED ISSUE #7: create a favicon and replace it with the default vite favicon
Currently we are using vite's default favicon,we need to replace it with a new one

### PR DESCRIPTION
**Pull request by younome71**
added a new favicon for the website

fixes #7

### CODE REVIEW

**Comment by sambhavgupta0705** [comment]
Hey @younome71 ,can you please convert it to svg format ,if possible.

**Comment by younome71** [comment]
> Hey @younome71 ,can you please convert it to svg format ,if possible.

Sir, the colors of the png files are getting compromised if it is converted to svg

**Comment by sambhavgupta0705** [comment]
Okay ,the design looks good to me 
@Anurag607 any suggestions???

**Comment by Anurag607** [comment]
Looks fantastic, well done @younome71!

**Comment by sambhavgupta0705** [comment]
@younome71 
remove the favicon file and rename favicon_2 file and then we are good to merge this one

**Review by sambhavgupta0705 — CHANGES_REQUESTED** [review]
Remove Favicon.png

**Comment by sambhavgupta0705** [comment]
@younome71 make it `favicon.png` instead of `Favicon.png`

**Comment by Anurag607** [comment]
@younome71 @sambhavgupta0705 if there are no more updates and changes, may be we can go ahead with the merge?

**Review by sambhavgupta0705 — APPROVED** [review]
Approved 👍🏻

**Pull request merged**
