### PR TITLE
Resolved the problem of dark mode in footer section

### LINKED ISSUE #79: [Feature Request]: Make footer compatible with dark mode
### Is your feature request related to a problem? Please describe.

.

### Describe the solution you'd like

.

### Describe alternatives you've considered

_No response_

### Developer Help

_No response_

### PR DESCRIPTION
**Pull request by abansal15**
## Overview

1. This PR fixes or fixes part of #79 .
2. This PR does the following: [Resolve the problem of dark mode]

## Essential Checklist

- [x] The PR title starts with "Fix #79 : ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

**Comment by abansal15** [comment]
@sambhavgupta0705 now it is working properly
image

**Comment by sambhavgupta0705** [comment]
@abansal15 your pr has merge conflicts

**Comment by abansal15** [comment]
@sambhavgupta0705 i think the one who has assigned the issue of removing email subscription has also changed the same file footer on which i am also working then what should i do now for removing the merge conflit.

**Comment by sambhavgupta0705** [comment]
@abansal15 watch this [merge conflicts tutorial](https://www.youtube.com/watch?v=nDRWhKc5Yd4&t=338s)

**Comment by abansal15** [comment]
@sambhavgupta0705 resolved the merge conflit

**Review by Anurag607 — APPROVED** [review]

**Comment by Anurag607** [comment]
@abansal15 @sambhavgupta0705 the changes look fine to me

**Pull request merged**
