### PR TITLE
Added icon of the website in the Navbar. Added the name of the websit…

### PR DESCRIPTION
**Pull request by younome71**
…e in the footer and alligned it with the github and linkedin links

## Overview
<This PR fixes part of the Issue #72
READ ME FIRST:
.
-->

1. This PR fixes or fixes part of #72 .
2. The PR does the following:-
   - Adds the icon of the website along with the name in the Navbar
   - Adds the Name and Icon of the website in the Footer along with the links and aligns them
## Essential Checklist

- [x]  The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)

- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

**Comment by sambhavgupta0705** [comment]
preview??? @younome71

**Comment by Anurag607** [comment]
@younome71 any updates on that preview?

**Comment by younome71** [comment]
@sambhavgupta0705 @Anurag607 I am unable to view the changes as the localhost is not working properly

**Comment by sambhavgupta0705** [comment]
@younome71 share a screenshot of what you are able to see

**Comment by younome71** [comment]
image
@sambhavgupta0705 @Anurag607 I have saved the .env file with the keys in the same folder as package.josn and still I am unable to see the website

**Pull request closed without merging**
