### PR TITLE
Imageswebp

### PR DESCRIPTION
**Pull request by AkashPaloju**
## Overview

1. This PR fixes of #48 .
2. This PR does the following: converted all png&jpeg images to .webp format and added them in public folder. Adjusted code in few files to adapt to the converted images format i.e. replaced respective_image.png/jpeg to respective_image.webp 

## Essential Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

https://github.com/bsoc-bitbyte/resource-sharing/assets/119884665/b58d6d5e-dabe-4937-98dc-51c6359edb76

@sambhavgupta0705 Please review it and kindly let me know if any further adjustments are required.

### CODE REVIEW

**Comment by sambhavgupta0705** [comment]
@AkashPaloju Great Work. 
Have you removed the previous images?

**Comment by AkashPaloju** [comment]
@sambhavgupta0705 No I didn't remove the previous images. I thought they will be used somewhere or sometime later by the maintaners.

**Comment by sambhavgupta0705** [comment]
@AkashPaloju I don't think we will be using them now.
Will prefer webp format. @Anurag607 what are your thoughts about it.

**Comment by sambhavgupta0705** [comment]
@AkashPaloju Please rename it and add some more details

**Comment by Anurag607** [comment]
@sambhavgupta0705 @AkashPaloju i don't think we need to convert the images right now, since, we will be using firebase storage to upload all the image assets and fetching from there. So we will worry about it then.

**Comment by sambhavgupta0705** [comment]
@AkashPaloju for now we are keeping this on hold

**Comment by sambhavgupta0705** [comment]
@AkashPaloju please resolve the conflicts and then we will merge it

**Comment by AkashPaloju** [comment]
@sambhavgupta0705 I have resolved the merge conflicts and removed the png&jpeg images as you  asked earlier. Please review it

**Review by sambhavgupta0705 — APPROVED** [review]

**Pull request merged**
