### PR TITLE
Functions for uplaoding images,pdfs and downloading(task-1)

### PR DESCRIPTION
**Pull request by RISHIKESHk07**
## Overview

-ISSUE #59 .
-This PR does the following: Created functions for uploading and downloading for images, pdfs .
-TASK 1 of issue  
-

https://github.com/bsoc-bitbyte/resource-sharing/assets/117551967/534eeca0-53f1-4d07-b23a-5e66be383f74

https://github.com/bsoc-bitbyte/resource-sharing/assets/117551967/9370a383-8f25-4921-9b04-3cb1b709f480

### CODE REVIEW

**Comment by Anurag607** [comment]
@RISHIKESHk07 please add a video showing you uploading 2-3 files (anything will work as long as it is pdf) and afterwards fetching them and then logging them in the browser console.

**Comment by sambhavgupta0705** [comment]
@RISHIKESHk07

**Comment by sambhavgupta0705** [comment]
@RISHIKESHk07 ??

**Comment by RISHIKESHk07** [comment]
> @RISHIKESHk07 ??



> @RISHIKESHk07 ??


Uploading Recording 2023-07-11 111645.mp4…

**Comment by RISHIKESHk07** [comment]
https://github.com/bsoc-bitbyte/resource-sharing/assets/117551967/79d24d00-163d-45c6-a76c-c2ebdff5b952




https://github.com/bsoc-bitbyte/resource-sharing/assets/117551967/e77acccf-7943-470c-9de1-c2fa5b98dbcb

**Comment by Anurag607** [comment]
@sambhavgupta0705 LGTM, your thoughts?

**Comment by sambhavgupta0705** [comment]
I am just worried about the UI @RISHIKESHk07 is this your final design

**Comment by Anurag607** [comment]
@sambhavgupta0705 the UI wasn't the issue

**Review by Anurag607 — APPROVED** [review]

**Comment by sambhavgupta0705** [comment]
@RISHIKESHk07 Thanks a lot for this PR

**Pull request merged**
